Test files and conftest.py
JAlvarezJarreta/MEvoLib pull request #9
Opened 2023-11-01 19:34 UTC by SMoragon

2023-11-04 12:35 UTC, nachorequeno requested changes

2023-11-04 12:35 UTC, nachorequeno commented on Tests/my_test_Inference__init_.py
> +        if set(term_names1) != set(term_names2):
```suggest
        return set(term_names1) == set(term_names2) and self._bitstrs(tree1) == self._bitstrs(tree2)
```

2023-11-04 12:35 UTC, nachorequeno commented on Tests/my_test_Inference_FastTree.py
> +        mocked_subprocess_output=run_mocker.get_mocked_output()
```suggest
        mocked_subprocess_output = run_mocker.get_mocked_output()
```

2023-11-21 20:19 UTC, JAlvarezJarreta requested changes
Besides the suggestions, it may also be useful to run `black` over these files.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_FastTree.py
> +from io import StringIO
Missing License header, and the imports should be in alphabetical order.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_FastTree.py
> +    def compare(self, tree1, tree2):
Missing type hints and docstring.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_FastTree.py
> +    def _bitstrs(self, tree):
Missing type hints and docstring.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_FastTree.py
> +        """
Why is this here?

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_RAxML.py
> +import os
Same as before.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_RAxML.py
> +        return set(term_names1) == set(term_names2) and self._bitstrs(tree1) == self._bitstrs(tree2)
Do not replicate code! If you need this in all your tests, better add this as utils or pytest element.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference_RAxML.py
> +       """
Why is this here?

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference__init_.py
> +from Bio.Phylo.Consensus import _BitString
This should be together in their own block.

2023-11-21 20:19 UTC, JAlvarezJarreta commented on Tests/my_test_Inference__init_.py
> +from contextlib import nullcontext as does_not_raise
Missing license header.

2023-11-22 10:22 UTC, SMoragon commented
I thank you the suggestions, but this was just for testing the tests. 
The real ones are in it's matching branch, "finished_tests".

2023-11-25 11:08 UTC, closed without merging